name       : perl-file-next
version    : '1.18'
release    : 8
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PE/PETDANCE/File-Next-1.18.tar.gz : f900cb39505eb6e168a9ca51a10b73f1bbde1914b923a09ecd72d9c02e6ec2ef
license    : Artistic-Perl-2.0
component  : programming.perl
summary    : File::Next - File-finding iterator
description: |
    File::Next - File-finding iterator
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
