name       : perl-file-next
version    : 1.16
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PE/PETDANCE/File-Next-1.16.tar.gz : 6965f25c2c132d0ba7a6f72b57b8bc6d25cf8c1b7032caa3a9bda8612e41d759
license    : Artistic-Perl-2.0
component  : programming.perl
summary    : File::Next - File-finding iterator
description: |
    File::Next - File-finding iterator
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
